---
# tasks file for roles/init_master

- name: Disabling SWAP
  shell: swapoff -a && cp /etc/fstab /etc/fstab_old && echo "#This is temp file for Kubernetes Installation, correct file is /etc/fstab_old" >> /etc/fstab && echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Initialise master
  shell: kubeadm init --apiserver-advertise-address={{ ansible_eth0.ipv4.address }}
  register: output
  ignore_errors: yes
  when: inventory_hostname in groups['master']

- name: Printing output on console
  debug: var=output.stdout_lines
  when: inventory_hostname in groups['master']

- name: Create .kube Folder
  file: 
    path: "{{ ansible_user_dir }}/.kube"
    state: directory
  when: inventory_hostname in groups['master']

- name: setting up kubeconfig
  copy: 
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  when: inventory_hostname in groups['master']

- name: configuring POD network
  shell: kubectl apply -f https://docs.projectcalico.org/v3.11/manifests/calico.yaml && sleep 20 && kubectl get nodes
  register: output
  when: inventory_hostname in groups['master']

- name: Printing output on console
  debug: var=output.stdout_lines
  when: inventory_hostname in groups['master']

- name: Generate join Command
  shell: kubeadm token create --print-join-command | grep -i kubeadm > /tmp/join-command.sh
  when: inventory_hostname in groups['master']

- name: Fetching Join Command from k8s master to ansible master
  fetch:
    src: /tmp/join-command.sh
    dest: join-command.sh
    mode: 755
    flat: yes
  when: inventory_hostname in groups['master']