---
# tasks file for roles/k8s

- name: setting up iptales for bridged traffic
  copy: 
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: reloading system ctl
  shell: sysctl --system

- name: running SE Linux in permissive mode
  shell: setenforce 0 && sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: copy kubernetes repo
  copy: 
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: '0755'

- name: installing kubernetes packges
  yum: 
    name: 
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes
      
- name: Starting & enabling kubernetes service
  service: 
    name: kubelet
    state: started
    enabled: yes